CREATE TABLE `author`
(
    author_id  BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100)                        NOT NULL,
    email      VARCHAR(255) UNIQUE                 NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);
